export const restaurantData = {
  restaurantData: {
    restaurantId: "538ba1a1-bf0d-47eb-9b88-054856703452",
    dealerId: null,
    userId: "01988d47-b5f1-7a3a-a7ed-77738062b0c9",
    name: "Liwa Cafe & Bistro",
    phoneNumber: "905058433855",
    latitude: 37.600327,
    longitude: 36.860684,
    city: "KAHRAMANMARAŞ",
    district: "ONİKİŞUBAT",
    neighbourhood: "SÜLEYMANŞAH MAHALLESİ",
    address:
      "Ondokuz Mayıs KYK Öğrenci Yurdu, Gençlik Bulvarı, Kumcağız Mahallesi, 19 Mayıs, Samsun, Black Sea Region, Turkey",
    isActive: true,
    imageAbsoluteUrl:
      "http://localhost:5210/images/restaurants/538ba1a1-bf0d-47eb-9b88-054856703452.jpg",
    defaultLang: "TR",
    slogan1: "Lezzetin Adı",
    slogan2:
      "İnsanları bir araya getiren hiçbir şey, güzel yemek kadar etkili değildir.",
    onlineOrder: true,
    inPersonOrder: true,
    hide: false,
    themeId: 1,
    maxDistance: 500,
    menuLang: "EN",
    tableOrderDiscountRate: 5,
    onlineOrderDiscountRate: 10,
    deliveryFee: 15,
    coverCharge: 10,
    minOrderAmount: 100,
    tenant: "popeyes",
    isSpecialPriceActive: true,
    specialPriceName: "Öğrenci İndirimi",
    googleAnalytics: "",
    licenseIsActive: true,
    maxTableOrderDistanceMeter: 500, // 500 metre - test için geçici değer
    checkTableOrderDistance: true,
    isReservationLicenseActive: true,
    tableNumber: 5, // Test için geçici değer
    moneySign: "₺",
    isReservationActive: true,
    WorkingHours: [
      { Day: 1, IsClosed: false, Open: "00:00", Close: "23:59" },
      { Day: 2, IsClosed: false, Open: "00:00", Close: "23:59" },
      { Day: 3, IsClosed: false, Open: "00:00", Close: "23:59" },
      { Day: 4, IsClosed: false, Open: "00:00", Close: "23:59" },
      { Day: 5, IsClosed: false, Open: "00:00", Close: "23:59" },
      { Day: 6, IsClosed: false, Open: "00:00", Close: "23:59" },
      { Day: 7, IsClosed: false, Open: "00:00", Close: "22:59" },
    ],
    SocialLinks: {
      facebookUrl: "https://facebook.com/popeyes",
      instagramUrl: "https://instagram.com/popeyes",
      tiktokUrl: null,
      youtubeUrl: null,
      whatsappUrl: "https://wa.me/905058433855",
    },
    Products: [
      {
        id: "prd-001-mercimek",
        sortOrder: 10,
        imageURL:
          "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop",
        name: "Mercimek Çorbası",
        description:
          "Kırmızı mercimek, soğan ve tereyağı ile hazırlanan klasik çorba.",
        recommendation: true,
        hide: false,
        categoryId: "cat-001-corbalar",
        categoryName: "Çorbalar",
        categoryImage:
          "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400",
        categorySortOrder: 1,
        subCategoryId: "sub-001-corba-klasik",
        subCategoryName: "Klasik",
        subCategoryImage: "",
        subCategorySortOrder: 1,
        isNoteAllowed: true,
        portions: [
          {
            id: "por-001-mercimek-normal",
            productId: "prd-001-mercimek",
            name: "Normal",
            price: 65,
            campaignPrice: 55,
            specialPrice: null,
            orderTags: [],
          },
        ],
      },
      {
        id: "prd-002-ezogelin",
        sortOrder: 20,
        imageURL:
          "https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?w=400&h=300&fit=crop",
        name: "Ezogelin Çorbası",
        description:
          "Bulgur, mercimek ve domatesle yapılan, limonla servis edilen çorba.",
        recommendation: false,
        hide: false,
        categoryId: "cat-001-corbalar",
        categoryName: "Çorbalar",
        categoryImage:
          "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400",
        categorySortOrder: 1,
        subCategoryId: null,
        subCategoryName: null,
        subCategoryImage: null,
        subCategorySortOrder: 0,
        portions: [
          {
            id: "por-002-ezogelin-normal",
            productId: "prd-002-ezogelin",
            name: "Normal",
            price: 68,
            campaignPrice: null,
            specialPrice: null,
            orderTags: [
              {
                id: "ot-001-acilik",
                name: "Acılık Seçimi",
                minSelected: 1,
                maxSelected: 1,
                freeTagging: false,
                sortOrder: 0,
                orderTagItems: [
                  {
                    id: "oti-001-acisiz",
                    name: "Acısız",
                    price: 0,
                    maxQuantity: 1,
                    isDefault: true,
                    isMandatory: true,
                    minQuantity: 1,
                    sortOrder: 0,
                  },
                  {
                    id: "oti-002-orta",
                    name: "Orta Acı",
                    price: 0,
                    maxQuantity: 1,
                    isDefault: false,
                    isMandatory: true,
                    minQuantity: 1,
                    sortOrder: 1,
                  },
                  {
                    id: "oti-003-acili",
                    name: "Acılı",
                    price: 0,
                    maxQuantity: 1,
                    isDefault: false,
                    isMandatory: true,
                    minQuantity: 1,
                    sortOrder: 2,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "prd-004-karniyarik",
        sortOrder: 10,
        imageURL:
          "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?w=400&h=300&fit=crop",
        name: "Karnıyarık",
        description:
          "Kıymalı harçla doldurulmuş patlıcan, pilav ile servis edilir.",
        recommendation: true,
        hide: false,
        categoryId: "cat-002-ana-yemekler",
        categoryName: "Ana Yemekler",
        categoryImage:
          "https://images.unsplash.com/photo-1574484284002-952d92456975?w=400",
        categorySortOrder: 2,
        subCategoryId: "sub-003-ana-evyemek",
        subCategoryName: "Ev Yemekleri",
        subCategoryImage: "",
        subCategorySortOrder: 1,
        isNoteAllowed: true,
        portions: [
          {
            id: "por-004-karniyarik-standart",
            productId: "prd-004-karniyarik",
            name: "Standart",
            price: 185,
            campaignPrice: null,
            specialPrice: null,
            orderTags: [
              {
                id: "ot-002-yan",
                name: "Yan Ürün Seçimi",
                minSelected: 0,
                maxSelected: 2,
                freeTagging: false,
                sortOrder: 0,
                orderTagItems: [
                  {
                    id: "oti-004-yogurt",
                    name: "Yoğurt",
                    price: 20,
                    maxQuantity: 1,
                    isDefault: false,
                    isMandatory: false,
                    minQuantity: 0,
                    sortOrder: 0,
                  },
                  {
                    id: "oti-005-salata",
                    name: "Mevsim Salata",
                    price: 30,
                    maxQuantity: 1,
                    isDefault: false,
                    isMandatory: false,
                    minQuantity: 0,
                    sortOrder: 1,
                  },
                  {
                    id: "oti-006-tursu",
                    name: "Turşu",
                    price: 15,
                    maxQuantity: 1,
                    isDefault: false,
                    isMandatory: false,
                    minQuantity: 0,
                    sortOrder: 2,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "prd-005-kuru-fasulye",
        sortOrder: 20,
        imageURL:
          "https://images.unsplash.com/photo-1574484284002-952d92456975?w=400&h=300&fit=crop",
        name: "Kuru Fasulye",
        description: "Etli kuru fasulye, pilav ve turşu ile servis edilir.",
        recommendation: false,
        hide: false,
        categoryId: "cat-002-ana-yemekler",
        categoryName: "Ana Yemekler",
        categoryImage:
          "https://images.unsplash.com/photo-1574484284002-952d92456975?w=400",
        categorySortOrder: 2,
        subCategoryId: "sub-003-ana-evyemek",
        subCategoryName: "Ev Yemekleri",
        subCategoryImage: "",
        subCategorySortOrder: 1,
        portions: [
          {
            id: "por-005-kuru-standart",
            productId: "prd-005-kuru-fasulye",
            name: "Standart",
            price: 175,
            campaignPrice: 160,
            specialPrice: 150,
            orderTags: [],
          },
        ],
      },
      {
        id: "prd-006-iskender",
        sortOrder: 30,
        imageURL:
          "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&h=300&fit=crop",
        name: "İskender Kebap",
        description:
          "Yoğurt, tereyağı ve domates sos ile servis edilen döner kebap.",
        recommendation: true,
        hide: false,
        categoryId: "cat-002-ana-yemekler",
        categoryName: "Ana Yemekler",
        categoryImage:
          "https://images.unsplash.com/photo-1574484284002-952d92456975?w=400",
        categorySortOrder: 2,
        subCategoryId: "sub-004-ana-kebaplar",
        subCategoryName: "Kebaplar",
        subCategoryImage: "",
        subCategorySortOrder: 2,
        isNoteAllowed: true,
        portions: [
          {
            id: "por-006-iskender-yarim",
            productId: "prd-006-iskender",
            name: "Yarım Porsiyon",
            price: 210,
            campaignPrice: null,
            specialPrice: null,
            orderTags: [
              {
                id: "ot-003-sos",
                name: "Sos Tercihi",
                minSelected: 0,
                maxSelected: 1,
                freeTagging: false,
                sortOrder: 0,
                orderTagItems: [
                  {
                    id: "oti-007-az-sos",
                    name: "Az Sos",
                    price: 0,
                    maxQuantity: 1,
                    isDefault: true,
                    isMandatory: false,
                    minQuantity: 0,
                    sortOrder: 0,
                  },
                  {
                    id: "oti-008-bol-sos",
                    name: "Bol Sos",
                    price: 10,
                    maxQuantity: 1,
                    isDefault: false,
                    isMandatory: false,
                    minQuantity: 0,
                    sortOrder: 1,
                  },
                ],
              },
            ],
          },
          {
            id: "por-007-iskender-tam",
            productId: "prd-006-iskender",
            name: "Tam Porsiyon",
            price: 285,
            campaignPrice: 255,
            specialPrice: null,
            orderTags: [
              {
                id: "ot-004-ekstra",
                name: "Ekstra Seçenekler",
                minSelected: 0,
                maxSelected: 3,
                freeTagging: false,
                sortOrder: 1,
                orderTagItems: [
                  {
                    id: "oti-009-yorum-yogurt",
                    name: "Ekstra Yoğurt",
                    price: 25,
                    maxQuantity: 2,
                    isDefault: false,
                    isMandatory: false,
                    minQuantity: 0,
                    sortOrder: 0,
                  },
                  {
                    id: "oti-010-ekmek",
                    name: "Ekstra Ekmek",
                    price: 10,
                    maxQuantity: 2,
                    isDefault: false,
                    isMandatory: false,
                    minQuantity: 0,
                    sortOrder: 1,
                  },
                  {
                    id: "oti-011-tereyagi",
                    name: "Ekstra Tereyağı",
                    price: 20,
                    maxQuantity: 1,
                    isDefault: false,
                    isMandatory: false,
                    minQuantity: 0,
                    sortOrder: 2,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "prd-007-adana",
        sortOrder: 10,
        imageURL:
          "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=400&h=300&fit=crop",
        name: "Adana Kebap",
        description:
          "Zırhla çekilmiş acılı kebap, köz biber ve soğan ile servis edilir.",
        recommendation: true,
        hide: false,
        categoryId: "cat-003-izgaralar",
        categoryName: "Izgaralar",
        categoryImage:
          "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=400",
        categorySortOrder: 3,
        subCategoryId: "sub-005-izgara-et",
        subCategoryName: "Et Izgara",
        subCategoryImage: "",
        subCategorySortOrder: 1,
        portions: [
          {
            id: "por-008-adana-1sis",
            productId: "prd-007-adana",
            name: "1 Şiş",
            price: 235,
            campaignPrice: null,
            specialPrice: null,
            orderTags: [
              {
                id: "ot-005-ekmek",
                name: "Ekmek Seçimi",
                minSelected: 1,
                maxSelected: 1,
                freeTagging: false,
                sortOrder: 0,
                orderTagItems: [
                  {
                    id: "oti-012-lavas",
                    name: "Lavaş",
                    price: 0,
                    maxQuantity: 1,
                    isDefault: true,
                    isMandatory: true,
                    minQuantity: 1,
                    sortOrder: 0,
                  },
                  {
                    id: "oti-013-pide",
                    name: "Pide",
                    price: 12,
                    maxQuantity: 1,
                    isDefault: false,
                    isMandatory: true,
                    minQuantity: 1,
                    sortOrder: 1,
                  },
                ],
              },
              {
                id: "ot-006-acilik-kebap",
                name: "Acı Seviyesi",
                minSelected: 1,
                maxSelected: 1,
                freeTagging: false,
                sortOrder: 1,
                orderTagItems: [
                  {
                    id: "oti-014-orta-aci",
                    name: "Orta Acı",
                    price: 0,
                    maxQuantity: 1,
                    isDefault: true,
                    isMandatory: true,
                    minQuantity: 1,
                    sortOrder: 0,
                  },
                  {
                    id: "oti-015-cok-aci",
                    name: "Çok Acı",
                    price: 0,
                    maxQuantity: 1,
                    isDefault: false,
                    isMandatory: true,
                    minQuantity: 1,
                    sortOrder: 1,
                  },
                ],
              },
            ],
          },
          {
            id: "por-008-adana-2sis",
            productId: "prd-007-adana",
            name: "2 Şiş",
            price: 420,
            campaignPrice: 380,
            specialPrice: null,
            orderTags: [],
          },
        ],
      },
      {
        id: "prd-008-urfa",
        sortOrder: 20,
        imageURL:
          "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&h=300&fit=crop",
        name: "Urfa Kebap",
        description:
          "Acısız kebap, közlenmiş biber ve soğan ile servis edilir.",
        recommendation: false,
        hide: false,
        categoryId: "cat-003-izgaralar",
        categoryName: "Izgaralar",
        categoryImage:
          "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=400",
        categorySortOrder: 3,
        subCategoryId: "sub-005-izgara-et",
        subCategoryName: "Et Izgara",
        subCategoryImage: "",
        subCategorySortOrder: 1,
        portions: [
          {
            id: "por-009-urfa-1sis",
            productId: "prd-008-urfa",
            name: "1 Şiş",
            price: 230,
            campaignPrice: 215,
            specialPrice: null,
            orderTags: [],
          },
        ],
      },
      {
        id: "prd-009-kofte",
        sortOrder: 30,
        imageURL:
          "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400&h=300&fit=crop",
        name: "Izgara Köfte",
        description:
          "Günlük hazırlanan dana köfte, pilav ve salata ile servis edilir.",
        recommendation: false,
        hide: false,
        categoryId: "cat-003-izgaralar",
        categoryName: "Izgaralar",
        categoryImage:
          "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=400",
        categorySortOrder: 3,
        subCategoryId: null,
        subCategoryName: null,
        subCategoryImage: null,
        subCategorySortOrder: 0,
        portions: [
          {
            id: "por-010-kofte-por",
            productId: "prd-009-kofte",
            name: "Porsiyon",
            price: 205,
            campaignPrice: null,
            specialPrice: 189,
            orderTags: [
              {
                id: "ot-007-pisir",
                name: "Pişirme Tercihi",
                minSelected: 1,
                maxSelected: 1,
                freeTagging: false,
                sortOrder: 0,
                orderTagItems: [
                  {
                    id: "oti-016-orta",
                    name: "Orta",
                    price: 0,
                    maxQuantity: 1,
                    isDefault: true,
                    isMandatory: true,
                    minQuantity: 1,
                    sortOrder: 0,
                  },
                  {
                    id: "oti-017-iyi",
                    name: "İyi Pişmiş",
                    price: 0,
                    maxQuantity: 1,
                    isDefault: false,
                    isMandatory: true,
                    minQuantity: 1,
                    sortOrder: 1,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "prd-010-tavuksis",
        sortOrder: 40,
        imageURL:
          "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=400&h=300&fit=crop",
        name: "Tavuk Şiş",
        description:
          "Marine edilmiş tavuk şiş, pilav ve salata ile servis edilir.",
        recommendation: true,
        hide: false,
        categoryId: "cat-003-izgaralar",
        categoryName: "Izgaralar",
        categoryImage:
          "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=400",
        categorySortOrder: 3,
        subCategoryId: "sub-006-izgara-tavuk",
        subCategoryName: "Tavuk Izgara",
        subCategoryImage: "",
        subCategorySortOrder: 2,
        portions: [
          {
            id: "por-011-tavuksis-por",
            productId: "prd-010-tavuksis",
            name: "Porsiyon",
            price: 195,
            campaignPrice: null,
            specialPrice: null,
            orderTags: [],
          },
        ],
      },
      {
        id: "prd-011-hamburger",
        sortOrder: 10,
        imageURL:
          "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop",
        name: "Klasik Hamburger",
        description: "Dana köfte, marul, domates ve özel burger sos ile.",
        recommendation: false,
        hide: false,
        categoryId: "cat-004-fast-food",
        categoryName: "Fast Food",
        categoryImage:
          "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400",
        categorySortOrder: 4,
        subCategoryId: "sub-007-fast-burger",
        subCategoryName: "Burger",
        subCategoryImage: "",
        subCategorySortOrder: 1,
        portions: [
          {
            id: "por-012-hamburger-tek",
            productId: "prd-011-hamburger",
            name: "Tek",
            price: 170,
            campaignPrice: 155,
            specialPrice: null,
            orderTags: [
              {
                id: "ot-010-ekmek-burger",
                name: "Ekmek Tipi",
                minSelected: 1,
                maxSelected: 1,
                freeTagging: false,
                sortOrder: 0,
                orderTagItems: [
                  {
                    id: "oti-023-klasik",
                    name: "Klasik",
                    price: 0,
                    maxQuantity: 1,
                    isDefault: true,
                    isMandatory: true,
                    minQuantity: 1,
                    sortOrder: 0,
                  },
                  {
                    id: "oti-024-tam-bugday",
                    name: "Tam Buğday",
                    price: 8,
                    maxQuantity: 1,
                    isDefault: false,
                    isMandatory: true,
                    minQuantity: 1,
                    sortOrder: 1,
                  },
                ],
              },
              {
                id: "ot-011-ekstra-burger",
                name: "Ekstra Malzeme",
                minSelected: 0,
                maxSelected: 3,
                freeTagging: true,
                sortOrder: 1,
                orderTagItems: [
                  {
                    id: "oti-025-cheddar",
                    name: "Cheddar",
                    price: 15,
                    maxQuantity: 2,
                    isDefault: false,
                    isMandatory: false,
                    minQuantity: 0,
                    sortOrder: 0,
                  },
                  {
                    id: "oti-026-jalapeno",
                    name: "Jalapeno",
                    price: 10,
                    maxQuantity: 2,
                    isDefault: false,
                    isMandatory: false,
                    minQuantity: 0,
                    sortOrder: 1,
                  },
                  {
                    id: "oti-027-caramel-onion",
                    name: "Karamelize Soğan",
                    price: 12,
                    maxQuantity: 1,
                    isDefault: false,
                    isMandatory: false,
                    minQuantity: 0,
                    sortOrder: 2,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "prd-012-cheeseburger",
        sortOrder: 20,
        imageURL:
          "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=400&h=300&fit=crop",
        name: "Cheeseburger",
        description: "Dana köfte, cheddar peyniri ve burger sos ile.",
        recommendation: true,
        hide: false,
        categoryId: "cat-004-fast-food",
        categoryName: "Fast Food",
        categoryImage:
          "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400",
        categorySortOrder: 4,
        subCategoryId: "sub-007-fast-burger",
        subCategoryName: "Burger",
        subCategoryImage: "",
        subCategorySortOrder: 1,
        portions: [
          {
            id: "por-013-cheese-menu",
            productId: "prd-012-cheeseburger",
            name: "Menü",
            price: 220,
            campaignPrice: null,
            specialPrice: 199,
            orderTags: [
              {
                id: "ot-012-patates",
                name: "Patates Boyutu",
                minSelected: 1,
                maxSelected: 1,
                freeTagging: false,
                sortOrder: 0,
                orderTagItems: [
                  {
                    id: "oti-028-kucuk",
                    name: "Küçük",
                    price: 0,
                    maxQuantity: 1,
                    isDefault: true,
                    isMandatory: true,
                    minQuantity: 1,
                    sortOrder: 0,
                  },
                  {
                    id: "oti-029-buyuk",
                    name: "Büyük",
                    price: 20,
                    maxQuantity: 1,
                    isDefault: false,
                    isMandatory: true,
                    minQuantity: 1,
                    sortOrder: 1,
                  },
                ],
              },
              {
                id: "ot-013-icecek-menu",
                name: "Menü İçeceği",
                minSelected: 1,
                maxSelected: 1,
                freeTagging: false,
                sortOrder: 1,
                orderTagItems: [
                  {
                    id: "oti-030-cola",
                    name: "Kola",
                    price: 0,
                    maxQuantity: 1,
                    isDefault: true,
                    isMandatory: true,
                    minQuantity: 1,
                    sortOrder: 0,
                  },
                  {
                    id: "oti-031-ayran",
                    name: "Ayran",
                    price: 0,
                    maxQuantity: 1,
                    isDefault: false,
                    isMandatory: true,
                    minQuantity: 1,
                    sortOrder: 1,
                  },
                  {
                    id: "oti-032-soda",
                    name: "Soda",
                    price: 0,
                    maxQuantity: 1,
                    isDefault: false,
                    isMandatory: true,
                    minQuantity: 1,
                    sortOrder: 2,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "prd-013-margarita",
        sortOrder: 30,
        imageURL:
          "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&h=300&fit=crop",
        name: "Margarita Pizza",
        description: "Mozzarella peyniri ve domates sos ile klasik pizza.",
        recommendation: false,
        hide: false,
        categoryId: "cat-004-fast-food",
        categoryName: "Fast Food",
        categoryImage:
          "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400",
        categorySortOrder: 4,
        subCategoryId: "sub-008-fast-pizza",
        subCategoryName: "Pizza",
        subCategoryImage: "",
        subCategorySortOrder: 2,
        portions: [
          {
            id: "por-014-pizza-orta",
            productId: "prd-013-margarita",
            name: "Orta (28 cm)",
            price: 240,
            campaignPrice: 219,
            specialPrice: null,
            orderTags: [],
          },
          {
            id: "por-015-pizza-buyuk",
            productId: "prd-013-margarita",
            name: "Büyük (33 cm)",
            price: 290,
            campaignPrice: null,
            specialPrice: null,
            orderTags: [
              {
                id: "ot-014-hamur",
                name: "Hamur Tercihi",
                minSelected: 1,
                maxSelected: 1,
                freeTagging: false,
                sortOrder: 0,
                orderTagItems: [
                  {
                    id: "oti-033-ince",
                    name: "İnce Hamur",
                    price: 0,
                    maxQuantity: 1,
                    isDefault: true,
                    isMandatory: true,
                    minQuantity: 1,
                    sortOrder: 0,
                  },
                  {
                    id: "oti-034-kalin",
                    name: "Kalın Hamur",
                    price: 0,
                    maxQuantity: 1,
                    isDefault: false,
                    isMandatory: true,
                    minQuantity: 1,
                    sortOrder: 1,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "prd-014-kunefe",
        sortOrder: 10,
        imageURL:
          "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&h=300&fit=crop",
        name: "Künefe",
        description: "Hatay usulü sıcak künefe, dondurma opsiyonludur.",
        recommendation: true,
        hide: false,
        categoryId: "cat-005-tatlilar",
        categoryName: "Tatlılar",
        categoryImage:
          "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400",
        categorySortOrder: 5,
        subCategoryId: "sub-009-tatli-serbetli",
        subCategoryName: "Şerbetli",
        subCategoryImage: "",
        subCategorySortOrder: 1,
        portions: [
          {
            id: "por-016-kunefe-por",
            productId: "prd-014-kunefe",
            name: "Porsiyon",
            price: 135,
            campaignPrice: null,
            specialPrice: null,
            orderTags: [
              {
                id: "ot-016-dondurma",
                name: "Dondurma",
                minSelected: 0,
                maxSelected: 1,
                freeTagging: false,
                sortOrder: 0,
                orderTagItems: [
                  {
                    id: "oti-036-sade",
                    name: "Dondurma Ekle",
                    price: 25,
                    maxQuantity: 1,
                    isDefault: false,
                    isMandatory: false,
                    minQuantity: 0,
                    sortOrder: 0,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "prd-015-firin-sutlac",
        sortOrder: 20,
        imageURL:
          "https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?w=400&h=300&fit=crop",
        name: "Fırın Sütlaç",
        description: "Fırında kızartılmış sütlaç, tarçın ile servis edilir.",
        recommendation: false,
        hide: false,
        categoryId: "cat-005-tatlilar",
        categoryName: "Tatlılar",
        categoryImage:
          "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400",
        categorySortOrder: 5,
        subCategoryId: "sub-010-tatli-sutlu",
        subCategoryName: "Sütlü",
        subCategoryImage: "",
        subCategorySortOrder: 2,
        portions: [
          {
            id: "por-017-sutlac-kase",
            productId: "prd-015-firin-sutlac",
            name: "Kase",
            price: 95,
            campaignPrice: 85,
            specialPrice: 79,
            orderTags: [],
          },
        ],
      },
      {
        id: "prd-016-ayran",
        sortOrder: 10,
        imageURL:
          "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400&h=300&fit=crop",
        name: "Ayran",
        description: "Soğuk, taze ayran.",
        recommendation: false,
        hide: false,
        categoryId: "cat-006-icecekler",
        categoryName: "İçecekler",
        categoryImage:
          "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400",
        categorySortOrder: 6,
        subCategoryId: "sub-011-icecek-soguk",
        subCategoryName: "Soğuk",
        subCategoryImage: "",
        subCategorySortOrder: 1,
        portions: [
          {
            id: "por-018-ayran-330",
            productId: "prd-016-ayran",
            name: "330 ml",
            price: 28,
            campaignPrice: null,
            specialPrice: null,
            orderTags: [],
          },
        ],
      },
      {
        id: "prd-017-cay",
        sortOrder: 20,
        imageURL:
          "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&h=300&fit=crop",
        name: "Çay",
        description: "Demlik çayı, ince belli bardakta servis edilir.",
        recommendation: true,
        hide: false,
        categoryId: "cat-006-icecekler",
        categoryName: "İçecekler",
        categoryImage:
          "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400",
        categorySortOrder: 6,
        subCategoryId: "sub-012-icecek-sicak",
        subCategoryName: "Sıcak",
        subCategoryImage: "",
        subCategorySortOrder: 2,
        portions: [
          {
            id: "por-019-cay-bardak",
            productId: "prd-017-cay",
            name: "Bardak",
            price: 18,
            campaignPrice: null,
            specialPrice: 15,
            orderTags: [
              {
                id: "ot-017-seker",
                name: "Şeker",
                minSelected: 0,
                maxSelected: 1,
                freeTagging: false,
                sortOrder: 0,
                orderTagItems: [
                  {
                    id: "oti-037-sekersiz",
                    name: "Şekersiz",
                    price: 0,
                    maxQuantity: 1,
                    isDefault: true,
                    isMandatory: false,
                    minQuantity: 0,
                    sortOrder: 0,
                  },
                  {
                    id: "oti-038-sekerli",
                    name: "Şekerli",
                    price: 0,
                    maxQuantity: 1,
                    isDefault: false,
                    isMandatory: false,
                    minQuantity: 0,
                    sortOrder: 1,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "prd-018-cola",
        sortOrder: 30,
        imageURL:
          "https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=400&h=300&fit=crop",
        name: "Kola",
        description: "Soğuk kola (kutu).",
        recommendation: false,
        hide: false,
        categoryId: "cat-006-icecekler",
        categoryName: "İçecekler",
        categoryImage:
          "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400",
        categorySortOrder: 6,
        subCategoryId: null,
        subCategoryName: null,
        subCategoryImage: null,
        subCategorySortOrder: 0,
        portions: [
          {
            id: "por-020-cola-330",
            productId: "prd-018-cola",
            name: "330 ml",
            price: 40,
            campaignPrice: 35,
            specialPrice: null,
            orderTags: [],
          },
        ],
      },
    ],
    Menus: [
      {
        id: 1,
        restaurantId: "538ba1a1-bf0d-47eb-9b88-054856703452",
        name: "Sabah Menüsü",
        plans: [
          {
            id: "plan-1-1",
            days: [1, 2, 3, 4, 5],
            startTime: "07:00",
            endTime: "11:00",
          },
          {
            id: "plan-1-2",
            days: [6, 7],
            startTime: "08:00",
            endTime: "12:00",
          },
        ],
        categoryIds: [
          "cat-001-corbalar",
          "cat-002-ana-yemekler",
          "cat-003-izgaralar",
          "cat-004-fast-food",
          "cat-005-tatlilar",
          "cat-006-icecekler",
        ],
      },
      {
        id: 2,
        restaurantId: "538ba1a1-bf0d-47eb-9b88-054856703452",
        name: "Öğle Menüsü",
        plans: [
          {
            id: "plan-2-1",
            days: [1, 2, 3, 4, 5],
            startTime: "11:30",
            endTime: "15:00",
          },
        ],
        categoryIds: [
          "cat-001-corbalar",
          "cat-002-ana-yemekler",
          "cat-003-izgaralar",
          "cat-004-fast-food",
          "cat-005-tatlilar",
          "cat-006-icecekler",
        ],
      },
      {
        id: 3,
        restaurantId: "538ba1a1-bf0d-47eb-9b88-054856703452",
        name: "Akşam Menüsü",
        plans: [
          {
            id: "plan-3-1",
            days: [1, 2, 3, 4, 5, 6, 7],
            startTime: "17:00",
            endTime: "23:00",
          },
        ],
        categoryIds: [
          "cat-001-corbalar",
          "cat-002-ana-yemekler",
          "cat-003-izgaralar",
          "cat-004-fast-food",
          "cat-005-tatlilar",
          //"cat-006-icecekler",
        ],
      },
    ],
    PaymentMethods: [
      { id: "pm-001", name: "Banka Kartı", enabled: true },
      { id: "pm-002", name: "Kredi Kartı", enabled: true },
      { id: "pm-003", name: "Nakit", enabled: true },
      { id: "pm-004", name: "Havale/EFT", enabled: false },
      { id: "pm-005", name: "Multinet", enabled: true },
      { id: "pm-006", name: "Sodexo", enabled: true },
    ],
  },
};
