/**
 * This code was generated by Builder.io.
 */
import React from "react";

const MarketplaceChart = () => {
  return (
    <div className="flex flex-col ml-5 w-[35%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow items-center pb-3 mx-auto w-full font-bold text-black bg-white rounded-lg border-2 border-solid border-slate-100 max-md:mt-6">
        <h2 className="self-stretch p-2.5 text-xl tracking-wide max-md:pr-5">
          Pazar Yerı
        </h2>
        <div className="flex mt-2.5 whitespace-nowrap">
          <div className="flex z-10 gap-2.5 justify-center self-end p-2.5 mt-3 text-xl tracking-wide bg-white rounded-xl shadow-2xl">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/d215d7e6254e6e0905fafe2e662c667d7b553deb5e8330e4740a4b095c8ff438?apiKey=1f4fb250339844f88428d2cbf4e019e9&&apiKey=1f4fb250339844f88428d2cbf4e019e9"
              alt=""
              className="shrink-0 aspect-[0.72] w-[18px]"
            />
            <div>35%</div>
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/e9b73e8c6f43cb3e3d17e7f07187ae7d3d52d2968fd031ce179a73a6408550a9?apiKey=1f4fb250339844f88428d2cbf4e019e9&&apiKey=1f4fb250339844f88428d2cbf4e019e9"
            alt="Pie chart"
            className="shrink-0 max-w-full aspect-[1.01] w-[157px]"
          />
          <div className="flex gap-2.5 justify-between self-start px-2.5 py-2.5 mt-28 text-xl tracking-normal bg-white rounded-lg shadow-2xl max-md:mt-10">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/b9990d3dde885451999ddf8a921a02178ab53c9aa33699be2681ea6908f9a506?apiKey=1f4fb250339844f88428d2cbf4e019e9&&apiKey=1f4fb250339844f88428d2cbf4e019e9"
              alt=""
              className="shrink-0 aspect-[0.75] w-[21px]"
            />
            <div className="my-auto">65%</div>
          </div>
        </div>
        <div className="mt-3.5 text-base tracking-normal text-neutral-400">
          856 Sipariş
        </div>
      </div>
    </div>
  );
};

export default MarketplaceChart;
