/**
 * This code was generated by Builder.io.
 */
import React from "react";

const RestaurantTable = () => {
  const restaurants = [
    { name: "Justin Lipshutz", sales: "1.000", amount: "100k", city: "Ankara" },
    { name: "Justin Lipshutz", sales: "1.000", amount: "100k", city: "Ankara" },
    { name: "Justin Lipshutz", sales: "1.000", amount: "100k", city: "Ankara" },
  ];

  return (
    <div className="flex flex-col w-[65%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow justify-center max-md:mt-6 max-md:max-w-full">
        <div className="flex flex-col px-7 pt-7 pb-11 bg-white rounded-md border-2 border-solid border-slate-100 max-md:px-5 max-md:max-w-full">
          <div className="flex gap-5 justify-between text-sm tracking-normal text-neutral-400 max-md:flex-wrap max-md:max-w-full">
            <div>Restoran Adı</div>
            <div>Toplam Satış</div>
            <div>Toplam Tutarı</div>
            <div>İl</div>
          </div>
          <hr className="shrink-0 mt-4 h-px border border-solid bg-zinc-100 border-zinc-100 max-md:max-w-full" />
          <div className="mt-7 max-md:max-w-full">
            {restaurants.map((restaurant, index) => (
              <div key={index} className="flex gap-5 mb-9 max-md:flex-col">
                <div className="flex flex-col w-2/5 max-md:ml-0 max-md:w-full">
                  <div className="text-sm font-bold text-black">
                    {restaurant.name}
                  </div>
                </div>
                <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
                  <div className="text-sm font-bold text-center text-black whitespace-nowrap">
                    {restaurant.sales}
                  </div>
                </div>
                <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
                  <div className="text-sm font-bold text-center text-black whitespace-nowrap">
                    {restaurant.amount}
                  </div>
                </div>
                <div className="flex flex-col ml-5 w-[10%] max-md:ml-0 max-md:w-full">
                  <div className="text-sm font-bold text-center text-black whitespace-nowrap">
                    {restaurant.city}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default RestaurantTable;
