/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SalesChart = () => {
  const months = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ];
  const heights = [81, 106, 127, 96, 61, 94, 110, 136, 117, 94, 76, 131];

  return (
    <div className="flex flex-col justify-center max-md:max-w-full mt-1.5">
      <div className="flex flex-col px-8 py-7 bg-white rounded-md border-2 border-solid border-slate-100 max-md:px-5 max-md:max-w-full">
        <div className="flex gap-5 w-full font-bold max-md:flex-wrap max-md:max-w-full">
          <h2 className="flex-auto my-auto text-2xl tracking-wide text-black">
            Toplam Satış
          </h2>
          <div className="flex gap-2.5 text-sm tracking-normal text-center text-blue-900 whitespace-nowrap">
            {["Pazaryeri", "Restoran", "Yıl", "Ay"].map((filter, index) => (
              <div
                key={index}
                className="flex gap-2.5 p-2.5 rounded-xl bg-neutral-100"
              >
                <div>{filter}</div>
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/3dc7c38522766ad325e58ad55fe13197d2e64a0ba5165bb0da74d1c0ff8e2fbf?apiKey=1f4fb250339844f88428d2cbf4e019e9&&apiKey=1f4fb250339844f88428d2cbf4e019e9"
                  alt=""
                  className="shrink-0 self-start w-4 aspect-square"
                />
              </div>
            ))}
          </div>
        </div>
        <div className="flex gap-5 mt-8 w-full max-md:flex-wrap max-md:max-w-full">
          <div className="flex flex-col self-start text-sm tracking-normal whitespace-nowrap text-stone-300">
            {[100, 80, 60, 40, 20].map((value, index) => (
              <div key={index} className={index > 0 ? "mt-10" : ""}>
                {value}
              </div>
            ))}
          </div>
          <div className="flex-auto max-md:max-w-full">
            <div className="flex gap-5 max-md:flex-col">
              {months.map((month, index) => (
                <div
                  key={month}
                  className={`flex flex-col ${
                    index === 7
                      ? "self-stretch text-center whitespace-nowrap"
                      : ""
                  }`}
                >
                  <div
                    className={`flex flex-col pt-${Math.floor(
                      heights[index] / 8
                    )} bg-indigo-50 rounded-lg`}
                  >
                    {index === 7 && (
                      <div className="px-2 py-0.5 bg-blue-900 rounded shadow-sm text-sm tracking-wider text-white">
                        77
                      </div>
                    )}
                    {index === 7 && (
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets/TEMP/e74fb19b7a2b0c8d6a3b37145fcc97edca5599a615ec443dc0634866b895bb10?apiKey=1f4fb250339844f88428d2cbf4e019e9&&apiKey=1f4fb250339844f88428d2cbf4e019e9"
                        alt=""
                        className="w-2 aspect-[1.33] fill-blue-900"
                      />
                    )}
                    <div
                      className={`shrink-0 bg-indigo-600 rounded-lg shadow-md h-[${heights[index]}px]`}
                    />
                  </div>
                  <div
                    className={`self-center mt-5 text-sm font-${
                      index === 7 ? "semibold" : "medium"
                    } tracking-normal text-${
                      index === 7 ? "stone-900" : "stone-300"
                    }`}
                  >
                    {month}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SalesChart;
