/**
 * This code was generated by Builder.io.
 */
import React from "react";

const StatCard = ({ title, value, unit, percentage, active, passive }) => {
  const isPositive = percentage >= 0;
  const percentageClass = isPositive
    ? "text-green-700 bg-green-600"
    : "text-red-700 bg-red-700";

  return (
    <div className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow px-5 pt-6 mx-auto w-full bg-white rounded-md border-2 border-solid border-slate-100 max-md:mt-3.5">
        <div className="flex gap-3.5 justify-between">
          <h2 className="my-auto text-base font-bold tracking-normal text-neutral-700">
            {title}
          </h2>
          <div
            className={`flex gap-1 justify-center px-1 py-1 text-sm tracking-normal whitespace-nowrap ${percentageClass} bg-opacity-10 rounded-[50px]`}
          >
            <img
              loading="lazy"
              src={`http://b.io/ext_${isPositive ? "1" : "2"}-`}
              alt=""
              className="shrink-0 my-auto w-3.5 aspect-square"
            />
            <div>{Math.abs(percentage)}%</div>
          </div>
        </div>
        <div className="flex gap-5 justify-between mt-1.5 whitespace-nowrap">
          <div className="flex flex-col justify-end pb-6">
            <div className="text-3xl font-bold tracking-wide text-neutral-800">
              {value.toLocaleString()}
            </div>
            <div className="mt-1.5 text-sm tracking-normal text-neutral-400">
              {unit}
            </div>
          </div>
          <div className="flex flex-col justify-between py-3.5 text-xs font-bold">
            <div className="flex gap-1.5 justify-between text-green-600">
              <div className="my-auto tracking-normal">{active}</div>
              <div className="px-4 py-1 border border-solid border-green-500 border-opacity-50 rounded-[54px]">
                Aktif
              </div>
            </div>
            <div className="flex gap-1.5 justify-between mt-1 text-slate-500">
              <div className="my-auto tracking-normal">{passive}</div>
              <div className="px-5 py-1 border border-solid border-slate-500 border-opacity-50 rounded-[54px]">
                Pasif
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default StatCard;
